[global]
pid=@RUN@/php-fpm.pid
error_log=@LOG@/php-fpm.log
daemonize=yes

[woo]
listen=@FPM_SOCKET@
listen.mode=0600
pm=ondemand
pm.max_children=4
pm.process_idle_timeout=30s
php_admin_value[memory_limit]=256M
php_admin_value[upload_max_filesize]=16M
php_admin_value[post_max_size]=16M
php_admin_value[error_log]=@LOG@/php-error.log
php_admin_flag[log_errors]=on
catch_workers_output=yes
